# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sriram
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website.
baseurl: "/" # the subpath of the site
url: "https://sri-ram-swaminathan.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic-1.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: CV
      slug: https://docs.google.com/document/d/1uVEKQkBt5hlOOZHhndw84KKXXm9KrzgH_wAgnsovfQY/copy
    - name: Blog
      slug: https://medium.com/@sriramthinksaboutthings
    - name: Work

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: Email
      link: mailto:intray.sri@gmail.com
    - name: LinkedIn
      link: http://linkedin.com/in/hisriram
    - name: GitHub
      link: http://github.com/sri-ram-swaminathan

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
